### ISSUE TITLE
Error deleting old backups when keep_last is set

### ISSUE THREAD

**Issue by zybron** [danielwelch/hassio-dropbox-sync#12]
I'm getting the following error below in the log during any execution of the addon. I suspect there may be something I need to do related to the new auth settings in Home Assistant, but I'm not certain what needs to be done.

[Info] keep_last option is set, cleaning up files...
Traceback (most recent call last):
  File "/keep_last.py", line 47, in <module>
    main(args.number)
  File "/keep_last.py", line 15, in main
    snapshot_info.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://hassio/snapshots

**Comment by zybron** [comment]
Hmm, well, I deleted a bunch of old snapshots manually and my automation ran successfully today. I'm going to assume there may have been some issue with those backup files and mark this closed and reopen if it happens again.
