### ISSUE TITLE
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://hassio/snapshots

### ISSUE THREAD

**Issue by wire67** [danielwelch/hassio-dropbox-sync#51]
This URL seems wrong for my install (on a VM) local domain is expected to be `http://homeassistant.local:8123/` 

``` An error occurred requesting /upload
 > Uploading "/backup/f911cabc.tar" to "/home_assistant_backups/f911cabc.tar"... FAILED
An error occurred requesting /upload
Some error occured. Please check the log.
[Info] keep_last option is set, cleaning up files...
Traceback (most recent call last):
  File "/keep_last.py", line 47, in <module>
    main(args.number)
  File "/keep_last.py", line 15, in main
    snapshot_info.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://hassio/snapshots
{"command":"upload"} 
```

**Comment by staspika** [comment]
Same problem here.

**Comment by MacL3an** [comment]
Same here. Just installed this and running:
```
Home Assistant 2023.1.2 
Supervisor 2022.12.1 
Operating System 9.4
```

**Comment by MacL3an** [comment]
Hmm, no commits since 2019. Perhaps this repo is dead 😢.
